server:
  port: 9801

spring:
  application:
    name: microservice-2022-0-2
    instance-id: ${spring.application.name}-01

eureka:
  instance:
    instance-id: ${spring.application.instance-id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    ip-address: 127.0.0.1
    metadata-map:
      startup: ${random.int}
      microservice:
        name: ${spring.application.name}
        instance-id: ${spring.application.instance-id}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8765/eureka/